# Generated by Django 3.2.4 on 2022-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='neredeVeri',
            field=models.CharField(default='ali', max_length=500),
            preserve_default=False,
        ),
    ]
